base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.Deployment.yaml
base/sourcegraph/codeintel-db/codeintel-db.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.Deployment.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 4.4.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47256)

release: sourcegraph@4.4.2

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.ConfigMap.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 4.5.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47836)

release: sourcegraph@4.5.0

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 4.5.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48151)

release: sourcegraph@4.5.1

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/monitoring/prometheus/prometheus.yml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.0.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48131)

release: sourcegraph@5.0.0

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50405)

release: sourcegraph@5.0.1

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.0.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50811)

release: sourcegraph@5.0.2

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.0.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/51302)

release: sourcegraph@5.0.3

---

base/sourcegraph/embeddings/embeddings.ConfigMap.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/embeddings/embeddings.Service.yaml
base/sourcegraph/embeddings/kustomization.yaml
base/sourcegraph/kustomization.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/custom/resources/kustomization.yaml
components/patches/embeddings-backend.yaml
components/remove/embedddings/kustomization.yaml
instances/template/kustomization.template.yaml

Backports Embeddings service from https://github.com/sourcegraph/deploy-sourcegraph-k8s/pull/27
See PR above

Add Embeddings service

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.0.4 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52092)

release: sourcegraph@5.0.4

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.0.5 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52745)

release: sourcegraph@5.0.5

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.0.6 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/53491)

release: sourcegraph@5.0.6

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/monitoring/prometheus/prometheus.yml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.1.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/49918)

release: sourcegraph@5.1.0

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.1.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54459)

release: sourcegraph@5.1.1

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.1.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54543)

release: sourcegraph@5.1.2

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 5.1.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54899)

release: sourcegraph@5.1.3

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/dind/patches/docker-daemon.ConfigMap.yaml
components/executors/k8s/executor.Deployment.yaml

This pull request is part of the Sourcegraph 5.1.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/55328)

release: sourcegraph@5.1.5

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

This pull request is part of the Sourcegraph 5.1.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56213)

release: sourcegraph@5.1.7

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

This pull request is part of the Sourcegraph 5.1.8 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.8)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56395)

release: sourcegraph@5.1.8

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

This pull request is part of the Sourcegraph 5.1.9 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.9)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56794)

release: sourcegraph@5.1.9

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/monitoring/prometheus/prometheus.yml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/github-proxy/github-proxy.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml
components/utils/migrator/resources/migrator.Job.yaml

Part of https://github.com/sourcegraph/sourcegraph/issues/56907
CI

release: sourcegraph@5.2.0

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/dind/patches/docker-daemon.ConfigMap.yaml
components/executors/k8s/executor.Deployment.yaml
components/utils/migrator/resources/migrator.Job.yaml

This pull request is part of the Sourcegraph 5.2.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/57319)

release: sourcegraph@5.2.1

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml
components/utils/migrator/resources/migrator.Job.yaml

This pull request is part of the Sourcegraph 5.2.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58310)

release: sourcegraph@5.2.3

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml
components/utils/migrator/resources/migrator.Job.yaml

This pull request is part of the Sourcegraph 5.2.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58967)

release: sourcegraph@5.2.5

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

{"version":"5.3.666","inputs":"server=v5.3.666","type":"patch"}

PRETEND PROMOTE RELEASE WIP: promote-release: build 5.3.666

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml
components/utils/migrator/resources/migrator.Job.yaml

This pull request is part of the Sourcegraph 5.2.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59830)

release: sourcegraph@5.2.7

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/monitoring/prometheus/prometheus.yml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/dind/patches/docker-daemon.ConfigMap.yaml
components/executors/k8s/executor.Deployment.yaml
components/utils/migrator/resources/migrator.Job.yaml

This pull request is part of the Sourcegraph 5.3.0 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60032)

release: sourcegraph@5.3.0

---

.github/PULL_REQUEST_TEMPLATE.md

update pr tmpl

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml
components/utils/migrator/resources/migrator.Job.yaml

This pull request is part of the Sourcegraph 5.3.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60691)

release: sourcegraph@5.3.1

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml
components/utils/migrator/resources/migrator.Job.yaml

This pull request is part of the Sourcegraph 5.3.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60972)

release: sourcegraph@5.3.2

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml
components/utils/migrator/resources/migrator.Job.yaml

This pull request is part of the Sourcegraph 5.3.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/61302)

release: sourcegraph@5.3.3

---

release.yaml

Check the auth status of GH before proceeding with a release.
- Manual testing

release: check gh auth status

---

release.yaml

Plugs in the release registry
---
Assumed correct, copied from deploy-sourcegraph

misc(release): plug release registry

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/embeddings/embeddings.Deployment.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

(promote) release: build v5.6.2535

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

(promote) release: build v5.7.0

---

.github/workflows/backport.yml

Standardizing across deploy-* repos
---
NA

feat/ci: add backport GHA

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

(promote) release: build v5.7.2474

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml

Update latest image tags
---
NA

Release: update image tags

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

(promote) release: build v5.8.0

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

update tags for 5.8.1579

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

(promote) release: build v5.9.1590

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

(promote) release: build v5.10.0

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

(promote) release: build v5.10.2832

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

This is a fixup PR to merge the v5.10.2832 release changes into main --https://github.com/sourcegraph/deploy-sourcegraph-k8s/pull/210
Generated, test via CI

Fix promote v5.10.2832

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

The other one has too many conflicts
---
CI

Release: 5.11.3601 Update images

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/repo-updater/repo-updater.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/symbols/symbols.StatefulSet.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

(promote) release: build v6.2.1106

---

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml
base/monitoring/grafana/grafana.StatefulSet.yaml
base/monitoring/jaeger/jaeger.Deployment.yaml
base/monitoring/node-exporter/node-exporter.DaemonSet.yaml
base/monitoring/otel-collector/otel-agent.DaemonSet.yaml
base/monitoring/otel-collector/otel-collector.Deployment.yaml
base/monitoring/prometheus/prometheus.Deployment.yaml
base/sourcegraph/blobstore/blobstore.Deployment.yaml
base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml
base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml
base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml
base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml
base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
base/sourcegraph/precise-code-intel/worker.Deployment.yaml
base/sourcegraph/redis/redis-cache.Deployment.yaml
base/sourcegraph/redis/redis-store.Deployment.yaml
base/sourcegraph/searcher/searcher.StatefulSet.yaml
base/sourcegraph/syntactic-code-intel/worker.Deployment.yaml
base/sourcegraph/syntect-server/syntect-server.Deployment.yaml
base/sourcegraph/worker/worker.Deployment.yaml
components/executors/dind/executor.Deployment.yaml
components/executors/k8s/executor.Deployment.yaml

(promote) release: build v6.3.4167

---

.tool-versions

Fix issue with mise in CI
---
CI

fix(rel): fix mise not installing kubectl
