base/monitoring/cadvisor/cadvisor.Service.yaml, base/monitoring/cadvisor/kustomization.yaml, base/monitoring/grafana/grafana.ConfigMap.yaml, base/monitoring/prometheus/prometheus.ConfigMap.yaml, base/sourcegraph/frontend/sourcegraph-frontend.Service.yaml, base/sourcegraph/redis/redis-cache.Service.yaml, base/sourcegraph/redis/redis-store.Service.yaml, base/sourcegraph/searcher/searcher.Service.yaml, base/sourcegraph/symbols/symbols.Service.yaml, base/sourcegraph/syntect-server/syntect-server.Deployment.yaml, base/sourcegraph/syntect-server/syntect-server.Service.yaml, components/monitoring/rbacs/prometheus/prometheus.ConfigMap.yaml, components/sizes/l/kustomization.yaml, components/sizes/l/patches/prometheus.yaml, components/sizes/m/kustomization.yaml, components/sizes/m/patches/prometheus.yaml, components/sizes/s/kustomization.yaml, components/sizes/s/patches/prometheus.yaml, components/sizes/xl/kustomization.yaml, components/sizes/xl/patches/prometheus.yaml, components/sizes/xs/kustomization.yaml, components/sizes/xs/patches/prometheus.yaml, examples/k3s/l/kustomization.yaml, examples/k3s/m/kustomization.yaml, examples/k3s/s/kustomization.yaml, examples/k3s/xl/kustomization.yaml
Included in this PR:
- create prometheus configmap for each instance size
- fix metrics endpoints for prometheus 
- fix k3s examples
=> Create prometheus configmap for each instance size

base/monitoring/prometheus/prometheus.ConfigMap.yaml, components/clusters/minikube/kustomization.yaml, components/utils/multi-version-upgrade/kustomization.yaml, instances/template/kustomization.template.yaml
Minor fixes:
- Fix minikube components
- Update component to make sure pgsql, codeintel-db, codeinsights-db are supported as Deployment and StatefulSets
---
pre-release
Tested locally in a minikube cluster
=> Minor component fixes

base/monitoring/prometheus/rbac/prometheus.ConfigMap.yaml, components/clusters/k3s/monitoring/patches/prometheus.ConfigMap.yaml, examples/k3s/kustomization.yaml, examples/k3s/l/kustomization.yaml, examples/k3s/m/kustomization.yaml, examples/k3s/s/kustomization.yaml, examples/k3s/xl/kustomization.yaml, examples/k3s/xs/kustomization.yaml
Update k3s to use configMap with privileged settings.
Also added the default namespace to k3s overlays
---
Deployed into a multi-nodes k3s cluster with metrics showing up:
```
NAME            STATUS   ROLES                  AGE   VERSION
sourcegraph-1   Ready    <none>                 11m   v1.25.6+k3s1
sourcegraph-0   Ready    control-plane,master   41m   v1.25.6+k3s1
```
```
default       github-proxy-5565f68966-t8rws                1/1     Running     0               8m51s
default       cadvisor-6p9gm                               1/1     Running     0               8m51s
default       node-exporter-78ztn                          1/1     Running     0               8m51s
default       cadvisor-wbbsv                               1/1     Running     0               8m51s
default …
```
=> fix: prometheus configMap issue for k3s

.github/PULL_REQUEST_TEMPLATE.md, base/monitoring/prometheus/prometheus.yml, base/sourcegraph/frontend/sourcegraph-frontend.ConfigMap.yaml, components/custom/old-patches/kustomization.yaml, components/services/searcher/deployment/kustomization.yaml, components/services/searcher/deployment/patches/searcher.Deployment.yaml, components/services/symbols/deployment/kustomization.yaml, components/services/symbols/deployment/patches/symbols.Deployment.yaml, components/utils/migrate-to-nonprivileged/kustomization.yaml, instances/template/kustomization.template.yaml
set default deployType to Kustomize
Include minor components touch up
---
Tested deployment with changes included in this PR:
```yaml
❯ k get pods -A
NAMESPACE     NAME                                             READY   STATUS    RESTARTS      AGE
default       blobstore-554b48dfb8-74hfg                       1/1     Running   0             19m
default       codeinsights-db-0                                2/2     Running   0             19m
default       codeintel-db-0                                   2/2     Running   1 (16m ago)   19m
default       github-proxy-699bdf7d88-2qqpc                    1/1     Running   0             19m
default       gitserver-0                                      1/1     Running   0             5m17s
default       grafana-0 …
```
=> update: set default deployType to Kustomize

.gitignore, .tool-versions, base/monitoring/prometheus/prometheus.yml, components/executors/k8s/README.md, components/executors/k8s/docker-daemon.ConfigMap.yaml, components/executors/k8s/executor.ConfigMap.yaml, components/executors/k8s/executor.Deployment.yaml, components/executors/k8s/executor.Service.yaml, components/executors/k8s/kustomization.yaml, components/executors/k8s/private-docker-registry/kustomization.yaml, components/executors/k8s/private-docker-registry/private-docker-registry.Deployment.yaml, components/executors/k8s/private-docker-registry/private-docker-registry.PersistentVolumeClaim.yaml, components/executors/k8s/private-docker-registry/private-docker-registry.Service.yaml, instances/template/kustomization.template.yaml
Migrate existing executors functionality from `sourcegraph/deploy-sourcegraph` as new Kustomize component.
Closes https://github.com/sourcegraph/sourcegraph/issues/51894
Closes https://github.com/sourcegraph/sourcegraph/issues/50599
---
Deployed `codeintel` executor using component and verified on `site-admin/executors` page.
=> Executors: migrate existing executors functionality from `sourcegraph/deploy-sourcegraph` 

README.md
A dead link for the Enterprise Guide was updated.
---
Verified manually.
=> Updating dead link

components/utils/migrator/resources/migrator.Job.yaml
Bumps the migrator to the latest version and unquotes it, otherwise `sg ops update-images` doesn't work (and is part of the release tool).
---
None necessary
=> bump migrator image tag and unquote for `sg ops update-images`

components/enable/private-registry/kustomization.yaml
Fixing the following bug:
```bash
$ kustomize build --load-restrictor LoadRestrictionsNone                            
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/Users/louis.jarvis@sourcegraph.com/git/deploy-sourcegraph-k8s/components/enable/private-registry': unable to find field \"spec.template.spec.initContainers.*.image\" in replacement target"
```
- To my knowledge there is no way to dynamically select `initContainers` among k8s resources or suppress this build error when an `initContainer` is not found
- Therefore, we need to specify which Deployments / StatefulSets contain an `initContainer`
---
tested locally
=> private registry patch should specify initContainers

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml, base/monitoring/grafana/grafana.StatefulSet.yaml, base/monitoring/jaeger/jaeger.Deployment.yaml, base/monitoring/node-exporter/node-exporter.DaemonSet.yaml, base/monitoring/otel-collector/otel-agent.DaemonSet.yaml, base/monitoring/otel-collector/otel-collector.Deployment.yaml, base/monitoring/prometheus/prometheus.Deployment.yaml, base/sourcegraph/blobstore/blobstore.Deployment.yaml, base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml, base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml, base/sourcegraph/embeddings/embeddings.Deployment.yaml, base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml, base/sourcegraph/gitserver/gitserver.StatefulSet.yaml, base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml, base/sourcegraph/pgsql/pgsql.StatefulSet.yaml, base/sourcegraph/precise-code-intel/worker.Deployment.yaml, base/sourcegraph/redis/redis-cache.Deployment.yaml, base/sourcegraph/redis/redis-store.Deployment.yaml, base/sourcegraph/repo-updater/repo-updater.Deployment.yaml, base/sourcegraph/searcher/searcher.StatefulSet.yaml, base/sourcegraph/symbols/symbols.StatefulSet.yaml, base/sourcegraph/syntect-server/syntect-server.Deployment.yaml, base/sourcegraph/worker/worker.Deployment.yaml, components/executors/dind/executor.Deployment.yaml, components/executors/k8s/executor.Deployment.yaml, components/utils/migrator/resources/migrator.Job.yaml
This pull request is part of the Sourcegraph 5.2.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58049)
=> release: sourcegraph@5.2.2

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml, base/monitoring/grafana/grafana.StatefulSet.yaml, base/monitoring/jaeger/jaeger.Deployment.yaml, base/monitoring/node-exporter/node-exporter.DaemonSet.yaml, base/monitoring/otel-collector/otel-agent.DaemonSet.yaml, base/monitoring/otel-collector/otel-collector.Deployment.yaml, base/monitoring/prometheus/prometheus.Deployment.yaml, base/sourcegraph/blobstore/blobstore.Deployment.yaml, base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml, base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml, base/sourcegraph/embeddings/embeddings.Deployment.yaml, base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml, base/sourcegraph/gitserver/gitserver.StatefulSet.yaml, base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml, base/sourcegraph/pgsql/pgsql.StatefulSet.yaml, base/sourcegraph/precise-code-intel/worker.Deployment.yaml, base/sourcegraph/redis/redis-cache.Deployment.yaml, base/sourcegraph/redis/redis-store.Deployment.yaml, base/sourcegraph/repo-updater/repo-updater.Deployment.yaml, base/sourcegraph/searcher/searcher.StatefulSet.yaml, base/sourcegraph/symbols/symbols.StatefulSet.yaml, base/sourcegraph/syntect-server/syntect-server.Deployment.yaml, base/sourcegraph/worker/worker.Deployment.yaml, components/executors/dind/executor.Deployment.yaml, components/executors/k8s/executor.Deployment.yaml, components/utils/migrator/resources/migrator.Job.yaml
This pull request is part of the Sourcegraph 5.2.6 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59481)
=> release: sourcegraph@5.2.6

go.mod, go.sum
[Context](https://sourcegraph.slack.com/archives/C05S2DYF4M8/p1708509146829369)
--- Update images lib
Next release should include updated images for executors and jaeger
=> release: udpate images lib

go.mod, go.sum
---
Cherry-pick images lib update to the release branch.
Plan is release should work fine.
=> cherry-pick images lib update

.buildkite/pipeline.yaml, release.yaml
Remove references to custom built `sg` now that new release process landed on main.
---
The failure is just before I noticed another bug, which got fixed in https://github.com/sourcegraph/sourcegraph/pull/61191
=> chg/rel: use default sg for release operations

.buildkite/pipeline.yaml, .tool-versions, README.md, release.yaml
Follow-up of https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/1008, see the description over there, it's exactly the same logic. 
---
- QA for the changes in that PR: same as the docker variant, mutiple runs
- https://buildkite.com/sourcegraph/deploy-sourcegraph-k8s/builds/318
- https://buildkite.com/sourcegraph/deploy-sourcegraph-k8s/builds/315
- tagging ![CleanShot 2024-03-24 at 12 55 58@2x](https://github.com/sourcegraph/deploy-sourcegraph-k8s/assets/10151/8c72ad1a-85af-4c95-9efe-9d3b6a740d85)
- QA for the result: compared the PR file by file against https://github.com/sourcegraph/deploy-sourcegraph-k8s/pull/101/files
=> Release update + tooling QA

release.yaml
Found a small typo in the notification link
None this is a link change
=> fix typo in notification link

release.yaml
use the public docker hub registry for public releases
CI and executed `sg ops update-images` locally (with the fix from https://github.com/sourcegraph/sourcegraph/pull/61592)
=> release: use docker hub registry for public releases

README.md
update docs links to point to the new docs site
This change converts from `docs.sourcegraph.com` to sourcegraph.com/docs`
not needed: README change
Check that the links point to the correct pages in the new docs site.
=> README.md links to docs

base/sourcegraph/redis/redis-cache.Deployment.yaml, base/sourcegraph/redis/redis-store.Deployment.yaml
fix redis startup
mirror: https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/458
---
Deploy locally
=> fix redis startup

base/sourcegraph/redis/redis-cache.Deployment.yaml, base/sourcegraph/redis/redis-store.Deployment.yaml
Follow fix after causing incident on dotcom from handling for no password incorrectly (https://sourcegraph.slack.com/archives/C074VSHMQSK/p1716835338964249)
---
Tested on kind cluster with both password supplied and not
=> fix the readiness probe fix, to correctly handle for passwords

base/monitoring/jaeger/jaeger-collector.Service.yaml, base/monitoring/jaeger/jaeger.Deployment.yaml
Resolves [REL-170](https://linear.app/sourcegraph/issue/REL-170/cve-2024-36129-deploy-sourcegraph-k8s)
---
Manual testing
=> fix(otel): update jaeger config

components/executors/k8s/rbac/executor.Role.yaml
`KUBERNETES_SINGLE_JOB_POD` mode was enabled by default in v5.6 with [PR 64088](https://github.com/sourcegraph/sourcegraph-public-snapshot/pull/64088) which includes a new requirement to manage ephemeral k8s Secrets.
---
N/A
=> Updated RBAC for KUBERNETES_SINGLE_JOB_POD mode

base/monitoring/grafana/grafana.ConfigMap.yaml
For [PS-83: Create pgsql datasource in Grafana](https://linear.app/sourcegraph/issue/PS-83/create-pgsql-datasource-in-grafana)
---
Tested on test instance for upgrades and new installs, with and without the env vars configured
I tried to change the existing ConfigMap just mounted as a single file inside the directory, so then I could just add Postgres via a separate ConfigMap via subDir mount, but that threw Grafana for a loop because the datasources.yml file is not declarative (ex. Terraform), but just an input ingestion method to Grafana's config state (maintained in a MongoDB inside the Grafana container?), and when the datasources.yml file gets a new inode on an existing instance, Grafana fails to start up, because we have default:true on Prometheus, so Grafana seeing the same …
=> Adding pgsql datasource for Grafana

base/monitoring/grafana/grafana.ConfigMap.yaml
While implementing these creds as Kubernetes secrets in the deploy-sourcegraph-helm repo in https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/568, the name of the env vars changed to match the format in the databaseAuth Helm template helper function, so I'm just updating the env var names to keep them consistent.
Issue:
https://linear.app/sourcegraph/issue/PS-91/update-env-vars-in-sgsg-to-match-helm-format
---
Manual testing
=> chore: Keep env var names consistent for Grafana pgsql datasource

base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml, base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml, base/sourcegraph/pgsql/pgsql.StatefulSet.yaml
We need to use the new postgres containers
---
CI
=> fix: use new 16 postgres containers

release.yaml
Add step to build process that creates a PR to update `main` with the latest release version.
---
- [NA] Update [CHANGELOG.md](https://github.com/sourcegraph/deploy-sourcegraph-k8s/blob/main/CHANGELOG.md)
- [NA] Update [K8s Upgrade notes](https://github.com/sourcegraph/sourcegraph/blob/main/doc/admin/updates/kubernetes.md)
- [NA] Kustomiz-specific changes
- [NA] Update sister repository: [deploy-sourcegraph-helm](https://github.com/sourcegraph/deploy-sourcegraph-helm)
- [NA] Update sister repository: [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker)
- [NA] Verify all images have a valid tag and SHA256 sum
CI during release cycle.
=> feat(rel): add step to release to update main with latest version

base/monitoring/cadvisor/cadvisor.DaemonSet.yaml, base/monitoring/grafana/grafana.StatefulSet.yaml, base/monitoring/jaeger/jaeger.Deployment.yaml, base/monitoring/node-exporter/node-exporter.DaemonSet.yaml, base/monitoring/otel-collector/otel-agent.DaemonSet.yaml, base/monitoring/otel-collector/otel-collector.Deployment.yaml, base/monitoring/prometheus/prometheus.Deployment.yaml, base/sourcegraph/blobstore/blobstore.Deployment.yaml, base/sourcegraph/codeinsights-db/codeinsights-db.StatefulSet.yaml, base/sourcegraph/codeintel-db/codeintel-db.StatefulSet.yaml, base/sourcegraph/frontend/sourcegraph-frontend.Deployment.yaml, base/sourcegraph/gitserver/gitserver.StatefulSet.yaml, base/sourcegraph/indexed-search/indexed-search.StatefulSet.yaml, base/sourcegraph/pgsql/pgsql.StatefulSet.yaml, base/sourcegraph/precise-code-intel/worker.Deployment.yaml, base/sourcegraph/redis/redis-cache.Deployment.yaml, base/sourcegraph/redis/redis-store.Deployment.yaml, base/sourcegraph/repo-updater/repo-updater.Deployment.yaml, base/sourcegraph/searcher/searcher.StatefulSet.yaml, base/sourcegraph/symbols/symbols.StatefulSet.yaml, base/sourcegraph/syntect-server/syntect-server.Deployment.yaml, base/sourcegraph/worker/worker.Deployment.yaml, components/executors/dind/executor.Deployment.yaml, components/executors/k8s/executor.Deployment.yaml
Update docker images to latest Sourcegraph release
---
CI
=> chore(rel): update latest tags

base/sourcegraph/gitserver/gitserver.StatefulSet.yaml
This adds a startup probe to gitserver so that it's not immediately killed while it's starting up and migrating the on-disk format for repos.
---
Passed linters, ran it locally, plan to exercise it when we deploy to s2 and dotcom.
=> add gitserver startup probe

.github/workflows/semgrep.yaml
Add semgrep scan to scan infra related files and changes
---
- CI 🟢 
- Semgrep scan should execute on all pull request changes
- Semgrep scan should execute on all pull request changes
=> security: add semgrep scan for scanning infra related files

components/clusters/k3s/kustomization.yaml, components/patches/frontend-vars.yaml
Linear issue [REL-812: Update deployment types](https://linear.app/sourcegraph/issue/REL-812/update-deployment-types)
Keeping env var name consistent between deployment repos
---
Test in Looker
=> Chore: Fix deployment types in telemetry

base/sourcegraph/kustomization.yaml, base/sourcegraph/syntactic-code-intel/kustomization.yaml, base/sourcegraph/syntactic-code-intel/worker.Deployment.yaml, base/sourcegraph/syntactic-code-intel/worker.Service.yaml
Add SCIW service to deployment.
---
Verified service is running and healthy:
```
deploy-sourcegraph-k8s 02-18-feat_rel_add_syntactic_code_intel_worker_service * um
❯ k get pods -n ns-sourcegraph
NAME                                           READY   STATUS    RESTARTS        AGE
blobstore-67ddf96c55-j5qlh                     1/1     Running   0               9m45s
codeinsights-db-0                              2/2     Running   0               9m44s
codeintel-db-0                                 2/2     Running   0               9m44s
gitserver-0                                    1/1     Running   2 (8m2s ago)    9m44s
grafana-0                                      1/1     Running   0               9m44s
indexed-search-0                               2/2     Running   0 …
```
=> feat(rel): add syntactic code intel worker service

release.yaml
Closes REL-1069
The release pipeline has been systematically failing in the `promoteToPublic.finalize` workflow with this error:
```
Warning: 1 uncommitted change
must be on a branch named differently than 'promote/release-v6.4.3889-update-main'
```
The final `github:pr` step in the `promoteToPublic.finalize` workflow was incorrectly trying to create a PR from the current branch to itself:
- **Current branch**: `promote/release-{{version}}-update-main`
- **Target branch**: `promote/release-{{version}}-update-main` ❌ (same branch!)
- **Should target**: `main` ✅
This happened because the variable `internal_branch` was set to the current branch name instead of the intended target branch.
This will have to be tested on a release
=> Fix(release): promoteToPublic.finalize github:pr update main target bug
